plugins {
    id 'java'
    id 'maven-publish'
}

description = 'census31-fwmt-canonical'
group = 'uk.gov.ons.census.fwmt'
version = rootProject.file('version.txt').text.trim()

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = 'census31-fwmt-canonical'
            version = version
            from components.java
        }
    }
}
